version: '3.3'
services:
  subscription:
    build:
      context: .
    ports:
      - '8085:8085'
    depends_on:
      - postgres-subscription
    networks:
      - pdznet
  postgres-subscription:
    image: 'postgres:12.3'
    environment:
      POSTGRES_DB: 'subscriptions_db'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '123'
    ports:
      - 5432:5432
    networks:
      - pdznet
networks:
  pdznet:
    external:
      name: pdz_network
